spring:
  flyway:
    validate-on-migrate: false
  datasource:
    url: jdbc:mysql://localhost:3306/registration?useTimezone=true&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    properties.hibernate.format_sql: false