CREATE TABLE IF NOT EXISTS COUNT
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(250) NOT NULL,
    ORIGINAL_VALUE DECIMAL(2, 0) NOT NULL,
    FIXED_VALUE DECIMAL(2, 0) NOT NULL,
    DUE_DATE DATE NOT NULL,
    PAYDAY DATE NOT NULL,
    DAYS_LATE INT NOT NULL,
    PRIMARY KEY (ID)
);