CREATE TABLE IF NOT EXISTS COUNT
(
    ID BIGINT auto_increment NOT NULL,
    NAME VARCHAR(250) NOT NULL,
    ORIGINAL_VALUE DECIMAL NOT NULL,
    FIXED_VALUE DECIMAL NOT NULL,
    DUE_DATE DATE NOT NULL,
    PAYDAY DATE NOT NULL,
    DAYS_LATE INT NOT NULL,
    PRIMARY KEY (ID)
);